package storage

import (
	"context"
	"encoding/base64"
	"errors"
	"io"
	"strings"
	"time"

	"github.com/QuantumNous/new-api/common"
	"github.com/QuantumNous/new-api/model"
	"github.com/QuantumNous/new-api/service"
	"gorm.io/gorm"
)

type creativeResultManifest struct {
	Items []creativeResultItem `json:"items"`
}

type creativeResultItem struct {
	B64JSON  string `json:"b64_json"`
	URL      string `json:"url"`
	MimeType string `json:"mime_type"`
	FileName string `json:"file_name"`
}

func ImportCreativeTaskManifest(ctx context.Context, task *model.CreativeTask) error {
	if task == nil || task.Status != model.CreativeTaskStatusImporting || strings.TrimSpace(task.ResultManifest) == "" {
		return errors.New("creative task has no importable result")
	}
	settings, err := service.GetCreativeStudioSettings()
	if err != nil || settings.DefaultFileChannelID == 0 {
		return errors.New("creative storage is unavailable")
	}
	var manifest creativeResultManifest
	if err := common.UnmarshalJsonStr(task.ResultManifest, &manifest); err != nil || len(manifest.Items) == 0 {
		return errors.New("invalid creative result manifest")
	}
	return importCreativeTaskResults(ctx, task, manifest.Items)
}

// ImportCreativeTaskResults imports generated bytes kept only in memory, such
// as Base64 returned by an upstream image API.
func ImportCreativeTaskResults(ctx context.Context, task *model.CreativeTask, items []map[string]string) error {
	results := make([]creativeResultItem, 0, len(items))
	for _, item := range items {
		results = append(results, creativeResultItem{B64JSON: item["b64_json"], URL: item["url"], MimeType: item["mime_type"], FileName: item["file_name"]})
	}
	return importCreativeTaskResults(ctx, task, results)
}

func importCreativeTaskResults(ctx context.Context, task *model.CreativeTask, items []creativeResultItem) error {
	if task == nil || task.Status != model.CreativeTaskStatusImporting || len(items) == 0 {
		return errors.New("creative task has no importable result")
	}
	settings, err := service.GetCreativeStudioSettings()
	if err != nil || settings.DefaultFileChannelID == 0 {
		return errors.New("creative storage is unavailable")
	}
	assets := make([]model.CreativeTaskAsset, 0, len(items))
	createdFileIDs := make([]uint64, 0, len(items))
	cleanup := func() {
		for _, fileID := range createdFileIDs {
			_, _ = Delete(ctx, fileID, &task.UserID)
		}
	}
	for position, item := range items {
		mimeType := strings.ToLower(strings.TrimSpace(item.MimeType))
		if (item.B64JSON == "" && item.URL == "") || (item.B64JSON != "" && !creativeMimeAllowed(settings, mimeType)) {
			return errors.New("invalid creative result item")
		}
		maxBytes := settings.MaxRasterBytes
		if mimeType == "image/svg+xml" {
			maxBytes = settings.MaxSVGBytes
		}
		var reader io.ReadCloser
		if item.B64JSON != "" {
			if int64(base64.StdEncoding.DecodedLen(len(item.B64JSON))) > maxBytes {
				return errors.New("generated asset exceeds size limit")
			}
			reader = io.NopCloser(base64.NewDecoder(base64.StdEncoding, strings.NewReader(item.B64JSON)))
		} else {
			remote, detectedMime, err := OpenGeneratedAssetURL(ctx, item.URL, maxBytes)
			if err != nil {
				return err
			}
			if mimeType != "" && detectedMime != mimeType {
				remote.Close()
				return errors.New("generated asset MIME type does not match its manifest")
			}
			mimeType = detectedMime
			if !creativeMimeAllowed(settings, mimeType) {
				remote.Close()
				return errors.New("generated asset MIME type is not allowed")
			}
			maxBytes = settings.MaxRasterBytes
			if mimeType == "image/svg+xml" {
				maxBytes = settings.MaxSVGBytes
			}
			reader = remote
		}
		if strings.TrimSpace(item.FileName) == "" || strings.TrimSpace(item.FileName) == "creative-image" {
			item.FileName = "creative-image." + generatedAssetSuffix(mimeType)
		}
		file, err := ImportGeneratedAsset(ctx, task.UserID, settings.DefaultFileChannelID, io.LimitReader(reader, maxBytes+1), GeneratedAssetInput{FileName: item.FileName, MimeType: mimeType, MaxBytes: maxBytes})
		reader.Close()
		if err != nil {
			cleanup()
			return err
		}
		createdFileIDs = append(createdFileIDs, file.ID)
		assets = append(assets, model.CreativeTaskAsset{TaskID: task.ID, UserFileID: file.ID, FileID: file.FileID, Role: "output", Position: position, MimeType: file.MimeType, FileSize: file.FileSize, FileName: file.FileName})
	}
	if err := model.DB.Transaction(func(tx *gorm.DB) error {
		for _, asset := range assets {
			if err := tx.Create(&asset).Error; err != nil {
				return err
			}
		}
		finishedAt := time.Now()
		return tx.Model(&model.CreativeTask{}).Where("id = ?", task.ID).Updates(map[string]any{"status": model.CreativeTaskStatusSucceeded, "result_manifest": "", "import_expires_at": nil, "finished_at": finishedAt}).Error
	}); err != nil {
		cleanup()
		return err
	}
	return nil
}

func creativeMimeAllowed(settings service.CreativeStudioSettings, mimeType string) bool {
	if !validGeneratedMime(mimeType) {
		return false
	}
	for _, allowed := range settings.AllowedImageMIMETypes {
		if mimeType == strings.ToLower(strings.TrimSpace(allowed)) {
			return true
		}
	}
	return false
}

func RecoverCreativeTaskImports(ctx context.Context, limit int) error {
	if limit <= 0 {
		limit = 100
	}
	var tasks []model.CreativeTask
	if err := model.DB.Where("status = ? AND import_expires_at > ?", model.CreativeTaskStatusImporting, time.Now()).Order("updated_at asc").Limit(limit).Find(&tasks).Error; err != nil {
		return err
	}
	for index := range tasks {
		task := &tasks[index]
		if err := ImportCreativeTaskManifest(ctx, task); err != nil {
			finishedAt := time.Now()
			if err := model.DB.Model(&model.CreativeTask{}).Where("id = ? AND status = ?", task.ID, model.CreativeTaskStatusImporting).Updates(map[string]any{"status": model.CreativeTaskStatusFailed, "error_code": "asset_import_failed", "error_message": err.Error(), "finished_at": finishedAt}).Error; err != nil {
				return err
			}
		}
	}
	return nil
}
